name: Android CI

on:
  push:
    branches: [ "main-github-action" ]
  pull_request:
    branches: [ "main-github-action" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2.0.10

        #1
    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
      run: |
        echo $ENCODED_STRING > keystore-b64.txt
        base64 -d keystore-b64.txt > keystore.jks

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Release apk
      env:
        RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      run: ./gradlew assembleRelease --stacktrace

#    - name: Get release file apk path
#      id: releaseApk
#      run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT

    - name: Run Tests
      run: ./gradlew lint test

#    - name: Zip Files
#      uses: papeloto/action-zip@v1
#      with:
#        files: ${{ steps.releaseApk.outputs.apkfile }}
#        dest: ${{ steps.releaseApk.outputs.apkfile }}.zip

    - name: Upload Build to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: app/build/outputs/
#        name: release-artifacts
#        path: ${{ steps.releaseApk.outputs.apkfile }}

    - name: Check and report lint results
      uses: hidakatsuya/action-report-android-lint@v1.1.3
      with:
        result-path: 'app/build/reports/lint-results-debug.xml'
