name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2.0.10

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build apk
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew lint test

    - name: Upload Build to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: app/build/outputs/apk/

    - name: Check and report lint results
      uses: hidakatsuya/action-report-android-lint@v1.1.3
      with:
        result-path: 'app/build/reports/lint-results-debug.xml'
