name: Android CI

on:
  push:
    branches: [ "main-github-action" ]
  pull_request:
    branches: [ "main-github-action" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle 
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2.0.10

    - name: Create local.properties
      env: 
        MOVIEDB_TOKEN_KEY: ${{ secrets.MOVIEDB_TOKEN_KEY }}
      run: |
        echo moviedb_token_key=$MOVIEDB_TOKEN_KEY > local.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Get release file apk path
      id: releaseApk
      run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT
    - name: Zip Files
      uses: papeloto/action-zip@v1
      with:
        files: ${{ steps.releaseApk.outputs.apkfile }}
        dest: ${{ steps.releaseApk.outputs.apkfile }}.zip
    - name: Upload Build to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-artifacts
        path: ${{ steps.releaseApk.outputs.apkfile }}
